
/** A chart option can consist of one or more metrics */
export enum EarningsChartPropertySelection {
    REVENUE = 'REVENUE',
    REVENUE_VS_NET_INCOME = 'REVENUE_VS_NET_INCOME',

    NET_PROFIT_MARGIN = 'NET_PROFIT_MARGIN',

    REVENUE_VS_COST = 'REVENUE_VS_COST',
    REVENUE_VS_GROSS_PROFIT = 'REVENUE_VS_GROSS_PROFIT',

    REVENUE_VS_STORES = 'STORES_VS_REVENUE',
    REVENUE_PER_STORES = 'STORES_PER_REVENUE',

    REVENUE_TYPE = 'REVENUE_TYPE',
    REVENUE_TYPE_PERCENTAGE = 'REVENUE_TYPE_PERCENTAGE',

    REVENUE_TYPE_PERCENTAGE_COLLECTIBLES = 'REVENUE_TYPE_PERCENTAGE_COLLECTIBLES',

    STORE_COUNT = 'STORE_COUNT',

    NET_INCOME = 'NET_INCOME',

    INTEREST_INCOME = 'INTEREST_INCOME',
    STOCKHOLDERS_EQUITY = 'STOCKHOLDERS_EQUITY',

    OPERATING_INCOME = 'OPERATING_INCOME',
    GROSS_PROFIT_VS_SGA = 'GROSS_PROFIT_VS_SGA',
    GROSS_MARGIN = 'GROSS_MARGIN',
    OPERATIONS_VS_SGA = 'OPERATIONS_VS_SGA',

    EPS = 'EPS',
    BOOK_VALUE_PER_SHARE = 'BOOK_VALUE_PER_SHARE',
}
