import { TimelineEventConfig } from "../timeline-items/timeline-item/timeline-event-config.interface";
import { TimelineEventType } from "../timeline-items/timeline-item/timeline-event-type.enum";


export const timelineEventConfigs: TimelineEventConfig[] = [
  {
    title: "GameStop Proposes to Acquire eBay",
    shortTitle: "Proposal for eBay",
    description: "GameStop submitted a non-binding proposal to acquire 100% of eBay Inc. at $125.00 per share in cash and stock.",
    dateYYYYMMDD: "2026-05-03",
    significance: 4,
    imagePath: "",
    tags: ["Corporate", "eBay"],
    types: [TimelineEventType.CORP],
    urls: [{ url: '/eBay', title: "Proposal to Acquire eBay", isLocal: true, }],
    showInViews: ["CURRENT", "CURRENT_MOBILE"],
  },
  {
    title: "GameStop Launches Power Packs",
    shortTitle: "GameStop Officially Launches Power Packs",
    description: "GameStop launched Power Packs:  \"an innovative digital experience from PSA and GameStop\" where collectors can purchase digital packs to unlock real, PSA-graded trading cards \"",
    dateYYYYMMDD: "2026-04-15",
    significance: 3,
    tags: ["Corporate", "Power Packs", "PSA", "TCG"],
    types: [TimelineEventType.CORP],
    urls: [{ url: '/trading-cards', title: 'GameStop Launches Power Packs', isLocal: true, }],
    showInViews: ["CURRENT", "CURRENT_MOBILE"],
  },
  {
    title: "Michael Burry",
    shortTitle: "Michael Burry",
    description: "After exiting GME 5 years prior, Michael Burry returns to GME and posts an article stating that he believes in Ryan Cohen",
    dateYYYYMMDD: "2026-01-26",
    significance: 3,
    tags: ["Michael Burry"],
    types: [TimelineEventType.OTHER],
    urls: [{ url: '/michael-burry', title: 'Michael Burry', isLocal: true, }],
    showInViews: [],
  },
  {
    title: "GameStop Announces Long-Term Performance Award for Ryan Cohen",
    shortTitle: "Performance Award",
    description: "GameStop Board of Directors has announced a proposed long-term performance award for CEO Ryan Cohen",
    dateYYYYMMDD: "2026-01-08",
    significance: 2,
    imagePath: "",
    tags: ["Corporate", "Ryan Cohen"],
    urls: [{ title: 'Michael Burry', isLocal: false, url: 'https://investor.gamestop.com/news-releases/news-details/2026/GameStop-Announces-Long-Term-Performance-Award-for-Ryan-Cohen/default.aspx', }],
    types: [TimelineEventType.CORP, TimelineEventType.RC],
    showInViews: [],
  },
  {
    title: "Ryan Cohen Interview with TBPN",
    shortTitle: "Ryan Cohen Interview with TBPN",
    description: "Ryan Cohen discusses GameStop, AI, other stuff",
    dateYYYYMMDD: "2025-10-20",
    significance: 2,
    tags: ["Ryan Cohen", "Media"],
    urls: [{ title: 'Ryan Cohen Interview with TBPN', isLocal: false, url: 'https://www.youtube.com/watch?v=UVSGKY4X018', }],
    types: [TimelineEventType.RC, TimelineEventType.MEDIA],
    showInViews: [],
  },
  {
    title: "GameStop Announces Dividend of Warrants to Shareholders",
    shortTitle: "Dividend of Warrants",
    description: "GameStop is giving shareholders warrants as a dividend, each allowing them to buy one share at $32 by Oct 30, 2026, which can also be traded separately on the NYSE.",
    dateYYYYMMDD: "2025-09-09",
    significance: 2,
    tags: ["[Corporate", "Dividends"],
    types: [TimelineEventType.CORP],
    urls: [{ title: 'Dividend of Warrants', isLocal: true, url: '/warrants', }],
    showInViews: ["CURRENT", "CURRENT_MOBILE"],
  },
  {
    title: "Ryan Cohen Does 2 Media Interviews",
    shortTitle: "RC Interviews",
    description: "Ryan Cohen does an interview with Andrew Sorkin of CNBC and then an interview with Charles Payne of Fox",
    dateYYYYMMDD: "2025-07-15",
    significance: 2,
    tags: ["Ryan Cohen", "Media"],
    urls: [
      { title: 'Interview on Fox Business', isLocal: false, url: 'https://www.reddit.com/r/Superstonk/comments/1m0pqqq/ryan_cohen_fox_business_interview_with_charles/', },
      { title: 'Interview with CNBC', isLocal: false, url: 'https://www.reddit.com/r/Superstonk/comments/1m0fitk/ryan_cohen_on_cnbc_july_15_2025/', }
    ],
    types: [TimelineEventType.RC, TimelineEventType.MEDIA],
    showInViews: [],
  },
  {
    title: "GameStop Raises $2.68 Billion",
    shortTitle: "GameStop Raises $2.68 B",
    description: "GameStop Raises $2.68 Billion via Convertible Senior Note Offering",
    dateYYYYMMDD: "2025-06-17",
    significance: 3,
    imagePath: "",
    tags: ["corporate"],
    types: [TimelineEventType.CORP],
    urls: [{ title: 'Convertible Senior Note Offering', isLocal: true, url: '/convertible-notes', }],
    showInViews: ["CURRENT", "CURRENT_MOBILE", "HISTORIC"],
  },
  {
    title: "GameStop Purchases 4,710 Bitcoin",
    shortTitle: "GameStop buys 4,710 BTC",
    description: "GameStop announces that it has purchased 4,710 bitcoin",
    dateYYYYMMDD: "2025-05-28",
    significance: 2,
    imagePath: "assets/misc/bitcoinlogo.png",
    tags: ["[corporate", "announcement",],
    types: [TimelineEventType.CORP],
    urls: [{ title: 'Investment Policy', isLocal: true, url: '/investment-policy', }],
    showInViews: [],
  },
  {
    title: "GameStop Raises $1.48 Billion",
    shortTitle: "GameStop Raises $1.48 B",
    description: "GameStop Raises $1.48 Billion via Convertible Senior Note Offering",
    dateYYYYMMDD: "2025-04-01",
    significance: 2,
    tags: ["corporate", "announcement"],
    types: [TimelineEventType.CORP],
    urls: [{ title: 'Convertible Senior Note Offering', isLocal: true, url: '/convertible-notes', }],
    showInViews: ["CURRENT", "HISTORIC"],
  },
  {
    title: "FY 2024 Results: Increasing Profitability and Value",
    shortTitle: "FY24: Increasing Profitability and Value",
    description: "Despite store closures and reduced revenue, GameStop shows improved profitability and the highest equity valuation in its history",
    dateYYYYMMDD: "2025-03-25",
    significance: 2,
    imagePath: "assets/info-pages/fy24-earnings-sankey.png",
    tags: ["corporate", "earnings", "10-Q", "10-K", "]"],
    types: [TimelineEventType.CORP],
    urls: [{ title: 'FY24: Increasing Profitability and Value', isLocal: true, url: '/fy24', }],
    showInViews: [],
  },
  {
    title: "GameStop Raised Billions of Dollars Amidst a Puzzling Surge in the GME Market Price",
    shortTitle: "The Burp",
    description: "GameStop raised billions of dollars via At-The-Market equity offerings amidst a puzzling surge in the GME market price that happened not too long after GameStop reported profitability for the first time in 6 years in fiscal year 2023 earnings results",
    dateYYYYMMDD: "2024-05-14",
    significance: 4,
    tags: ["Corporate", "ATM", "dilution", "balance sheet", "cash", "raise"],
    types: [TimelineEventType.OTHER],
    urls: [{ title: 'The Burp of May 2024', isLocal: true, url: '/burp', }],
    showInViews: ["CURRENT", "CURRENT_MOBILE", "HISTORIC"],
  },
  {
    title: "GameStop Raises $2.14 Billion",
    shortTitle: "GameStop Raises $2.14 Billion",
    description: "GameStop raises approximately $2.137 billion via At-The-Market equity offering",
    dateYYYYMMDD: "2024-06-11",
    significance: 4,
    tags: ["Corporate", "ATM", "dilution", "balance sheet", "cash", "raise"],
    types: [TimelineEventType.CORP],
    urls: [{ title: '2024 ATMs', isLocal: true, url: '/atms', }],
    showInViews: ["CURRENT", "HISTORIC"],
  },
  {
    title: "FY 2023 Results:  Profitable for the First Time in 6 Years",
    shortTitle: "Profitable",
    description: "",
    dateYYYYMMDD: "2024-03-26",
    significance: 4,
    imagePath: "assets/earnings-sankey/fy23-sankey.jpg",
    tags: ["corporate", "earnings"],
    types: [TimelineEventType.CORP],
    urls: [{ title: 'GameStop was profitable for the first time in 6 years', isLocal: true, url: '/fy23', }],
    showInViews: ["CURRENT", "CURRENT_MOBILE", "HISTORIC"],
  },
  {
    title: "GameStop Reports Registered Share Count for the First Time",
    shortTitle: "DRS",
    description: "GameStop reports for the first time the number of shares that have been directly registered",
    dateYYYYMMDD: "2021-12-08",
    significance: 4,
    tags: ["corporate", "earnings", "10-Q", "drs"],
    types: [TimelineEventType.DRS, TimelineEventType.CORP],
    urls: [{ title: 'DRS - Direct Registration System', isLocal: true, url: '/drs', }],
    showInViews: ["CURRENT", "CURRENT_MOBILE", "HISTORIC"],
  },
  {
    title: "The Sneeze",
    shortTitle: "The Sneeze",
    description: "Facing untenable risk and existential elimination, a multitude of interested Wall St participants including brokerages, clearing houses, market makers, hedge funds, and other participants, in unison, take the unprecedented action of disabling any further purchasing of GME by retail shareholders.",
    dateYYYYMMDD: "2021-01-28",
    significance: 5,
    imagePath: "assets/misc/gme-go-brrr.png",
    tags: ["broker-dealers", "corruption", "wall st", "sneeze", "squeeze"],
    types: [TimelineEventType.OTHER],
    urls: [{ title: 'The Sneeze of January 2021', isLocal: true, url: '/sneeze', }],
    showInViews: ["CURRENT", "CURRENT_MOBILE", "HISTORIC"],
  },
  {
    title: "GameStop Raises $0.93 Billion",
    shortTitle: "",
    description: "GameStop raises approximately $0.93 billion via ATM equity offering",
    dateYYYYMMDD: "2024-05-24",
    significance: 2,
    tags: ["Corporate", "ATM", "dilution", "balance sheet", "cash", "raise",],
    types: [TimelineEventType.CORP],
    urls: [{ title: '2024 ATMs', isLocal: true, url: '/atms', }],
    showInViews: ["CURRENT"],
  },
  {
    title: "Roaring Kitty Is Back With Memes",
    shortTitle: "",
    description: "After 3 years of absence, Roaring Kitty posts a long series of memes and videos on X",
    dateYYYYMMDD: "2024-05-13",
    significance: 2,
    imagePath: "assets/dfv/rk-2024-05-12.png",
    tags: ["dfv", "social media",],
    urls: [
      { title: 'A thread of @TheRoaringkitty compilations from the week of May 13 - May 17 in order', isLocal: false, url: "https://x.com/roaringpika/status/1792256415794425863", },
      { title: 'Keith Gill AKA Roaring Kitty did not make GME go up 74% today!', isLocal: false, url: 'https://www.reddit.com/r/Superstonk/comments/1crbfdd/keith_gill_aka_roaring_kitty_did_not_make_gme_go/', }
    ],
    types: [TimelineEventType.SOCIAL_MEDIA],
    showInViews: ["CURRENT"],
  },
  {
    title: "GameStop Raises $550 M",
    shortTitle: "",
    description: "The Company ultimately sold 5,000,000 shares of common stock and generated aggregate gross proceeds before commissions and offering expenses of approximately $1,126,000,000.",
    dateYYYYMMDD: "2021-06-22",
    significance: 2,
    tags: ["corporate", "atm",],
    types: [TimelineEventType.CORP],
    urls: [{ title: '2021 ATMs', isLocal: true, url: '/atms', }],
    showInViews: ["CURRENT"],
  },
  {
    title: "Ryan Cohen Elected as Chairman of the Board of Directors",
    shortTitle: "Ryan Cohen: Chairman",
    description: "GameStop releases Q1 2021 financial results.  Ryan Cohen elected as chairman.  Matt Furlong appointed as CEO.",
    dateYYYYMMDD: "2021-06-09",
    significance: 3,
    tags: ["corporate", "earnings", "ryan cohen", "board of directors", "chairman", "ceo", "matt furlong",],
    types: [TimelineEventType.CORP, TimelineEventType.MEDIA],
    urls: [{ title: 'The Turnaround of GameStop Begins', isLocal: true, url: '/turnaround', }],
    showInViews: ["CURRENT", "CURRENT_MOBILE", "HISTORIC"],
  },
  {
    title: "GameStop Raises $1.1 B",
    shortTitle: "",
    description: "The Company ultimately sold 3,500,000 shares of common stock and generated aggregate gross proceeds before commissions and offering expenses of approximately $551,000,000",
    dateYYYYMMDD: "2021-04-05",
    significance: 2,
    tags: ["corporate", "atm"],
    types: [TimelineEventType.CORP],
    urls: [{ title: '2021 ATMs', isLocal: true, url: '/atms', }],
    showInViews: ["CURRENT"],
  },
  {
    title: "Game Stopped? Congressional Hearing, Featuring Keith Gill",
    shortTitle: "I like the stock",
    description: "Game Stopped? Who Wins and Loses When Short Sellers, Social Media, and Retail Investors Collide. Keith Gill testifies before congress House Committee on Financial Services",
    dateYYYYMMDD: "2021-02-18",
    significance: 2,
    imagePath: "assets/misc/i-like-the-stock.png",
    tags: ["short sellers", "dfv", "social media", "congress", "regulators", "oversight", "lawsuit"],
    urls: [
      { title: 'A thread of @TheRoaringkitty compilations from the week of May 13 - May 17 in order', isLocal: true, url: "/keith-gill", },
      { title: '"I like the stock:" Keith Gill AKA "Roaring Kitty" defends GameStop posts before Congress ', isLocal: false, url: 'https://www.youtube.com/watch?v=OARREl39syQ', }
    ],
    types: [TimelineEventType.SOCIAL_MEDIA],
    showInViews: ["CURRENT", "CURRENT_MOBILE", "SNEEZE", "SNEEZE_MOBILE"],
  },
  {
    title: "Nintendo Switch Released",
    shortTitle: "",
    description: "Nintendo Switch released",
    dateYYYYMMDD: "2017-03-03",
    tags: ["nintendo", "video game", "console"],
    significance: 4,
    types: [TimelineEventType.OTHER],
    showInViews: ["HISTORIC"],
  },
  {
    title: "Xbox One Released",
    shortTitle: "",
    description: "Xbox One released",
    dateYYYYMMDD: "2013-11-22",
    tags: ["microsoft", "xbox", "video game", "console"],
    significance: 4,
    types: [TimelineEventType.OTHER],
    showInViews: ["HISTORIC"],
  },
  {
    title: "Playstation 4 (PS4) Released",
    shortTitle: "",
    description: "Playstation 4 (PS4) released",
    dateYYYYMMDD: "2013-11-15",
    significance: 4,
    tags: ["playstation", "sony", "video game", "console",],
    types: [TimelineEventType.OTHER],
    showInViews: ["HISTORIC"],
  },
  {
    title: "Playstation 3 (PS3) Released",
    shortTitle: "",
    description: "Playstation 3 (PS3) released",
    dateYYYYMMDD: "2006-11-17",
    tags: ["playstation", "sony", "video game", "console"],
    significance: 4,
    types: [TimelineEventType.OTHER],
    showInViews: ["HISTORIC"],
  },
  {
    title: "Nintendo Wii released",
    shortTitle: "",
    description: "Nintendo Wii released",
    dateYYYYMMDD: "2006-11-19",
    tags: ["nintendo", "video game", "console",],
    significance: 4,
    types: [TimelineEventType.OTHER],
    showInViews: ["HISTORIC"],
  },
  {
    title: "Xbox 360 released",
    shortTitle: "",
    description: "Xbox 360 released",
    dateYYYYMMDD: "2005-11-22",
    significance: 4,
    tags: ["microsoft", "xbox", "video game", "console"],
    types: [TimelineEventType.OTHER],
    showInViews: ["HISTORIC"],
  },
  {
    title: "GameStop Collaborating With PSA",
    shortTitle: "Trading Cards",
    description: "GameStop announced a collaboration with PSA, becoming an authorized PSA dealer",
    dateYYYYMMDD: "2024-10-15",
    significance: 2,
    tags: ["Corporate",],
    types: [TimelineEventType.CORP],
    urls: [{ title: 'GameStop expands efforts in trading cards', isLocal: true, url: '/trading-cards', }],
    showInViews: ["CURRENT", "CURRENT_MOBILE"],
  },
  {
    title: "GameStop Raises Approximately $0.4 B",
    shortTitle: "",
    description: "GameStop raises approximately $0.4 B via ATM equity offering",
    dateYYYYMMDD: "2024-09-23",
    significance: 2,
    tags: ["Corporate", "ATM", "dilution", "balance sheet", "cash", "raise"],
    types: [TimelineEventType.CORP],
    urls: [{ title: '2021 ATMs', isLocal: true, url: '/atms', }],
    showInViews: [],
  },
  {
    title: "Roaring Kitty Live Stream - June 7, 2024",
    shortTitle: "Roaring Kitty Live Stream",
    description: "Roaring Kitty does a live stream with over 500 thousand viewers",
    dateYYYYMMDD: "2024-06-07",
    significance: 3,
    imagePath: "assets/dfv/rk-2024-06-07.png",
    tags: ["roaring kitty", "social media", "youtube"],
    urls: [
      { title: 'Roaring Kitty Live Stream - June 7, 2024 ', isLocal: false, url: "https://www.youtube.com/watch?v=U1prSyyIco0", },
      { title: 'CNBC getting owned by DFV ', isLocal: false, url: 'https://www.reddit.com/r/Superstonk/comments/1dagsyu/cnbc_getting_owned_by_dfv/', }
    ],
    types: [TimelineEventType.SOCIAL_MEDIA],
    showInViews: ["CURRENT", "CURRENT_MOBILE", "SNEEZE", "SNEEZE_MOBILE"],
  },
  {
    title: "GameStop Makes Significant Changes to Investment Policy",
    shortTitle: "",
    description: "Ryan Cohen has received authority to manage GameStop's portfolio of investments.",
    dateYYYYMMDD: "2023-12-06",
    significance: 2,
    tags: ["corporate", "earnings", "10-Q", "investment policy", "ryan cohen", "policy"],
    types: [TimelineEventType.CORP, TimelineEventType.RC],
    urls: [{ title: 'Investment Policy', isLocal: true, url: '/investment-policy', }],
    showInViews: ["CURRENT"],
  },
  {
    title: "GameStop Announces Election of Ryan Cohen as Chief Executive Officer",
    shortTitle: "",
    description: "",
    dateYYYYMMDD: "2023-09-28",
    significance: 2,
    tags: ["corporate", "announcement", "ceo", "ryan cohen"],
    types: [TimelineEventType.CORP, TimelineEventType.RC],
    urls: [
      { title: 'Turnaround: in progress', isLocal: true, url: '/turnaround', },
      { title: 'Turnaround: in progress', isLocal: false, url: 'https://web.archive.org/web/20231010164723/https://www.reddit.com/r/Superstonk/comments/16urjos/ryan_cohens_email_to_corporate_employees_and/', }
    ],
    showInViews: ["CURRENT"],
  },
  {
    title: "Reddit Permanently Bans the r/DRSyourGME Subreddit",
    shortTitle: "",
    description: "Shortly after GME shareholders published their data from the viewing of the stockholders list in the r/DRSyourGME subreddit, Reddit bans that subreddit",
    dateYYYYMMDD: "2023-06-14",
    significance: 2,
    imagePath: "assets/misc/DRSyourGME-banned.PNG",
    tags: ["reddit", "censorship", "drs"],
    types: [TimelineEventType.DRS, TimelineEventType.SOCIAL_MEDIA],
    urls: [
      { title: 'DRS Timeline', isLocal: true, url: '/drs-timeline', },
      { title: 'Superstonk Fireside Chat', isLocal: false, url: 'https://www.reddit.com/r/Superstonk/comments/145j69y/fireside_chat_692023_on_the_topic_of_doxxing_and/?sort=top', }
    ],
    // expandedLinks: ["", "https://twitter.com/SusanneTrimbath/status/1667275379806019584", "https://www.reddit.com/r/Superstonk/comments/145gp90/drsusanne_trimbath_on_twitter/"],
    showInViews: ["CURRENT"],
  },
  {
    title: "Jim Cramer Confesses the Stock Market Is Rigged",
    shortTitle: "",
    description: "Cramer: '[GME] was totally rigged. Its okay. It was rigged. I called it out, in one of those movies I called it out. I dont want any touching that. I like great American stories. I dont like the hokum.'",
    dateYYYYMMDD: "2023-02-03",
    significance: 2,
    imagePath: "assets/media/cramer-2023-02-03.png",
    tags: ["propaganda", "Jim Cramer", "scam", "fraud", "crime", "FTX", "sneeze", "robinhood", "media", "corruption"],
    urls: [
      { title: 'Market Tactics and Manipulation', isLocal: true, url: '/market-tactics', },
      { title: 'A new hero is born! Shout-out to Nathan in Florida!', isLocal: false, url: 'https://www.reddit.com/r/Superstonk/comments/10siamz/a_new_hero_is_born_shoutout_to_nathan_in_florida/?sort=top', }
    ],
    types: [TimelineEventType.MEDIA],
    showInViews: ["CURRENT",],
  },
  {
    title: "CNBC Watches Superstonk",
    shortTitle: "",
    description: "Despite never acknowledging the existence of GME investor subreddits like Superstonk, CNBC noticed conversations that were critical of them that were happening on superstonk and felt the need to make a segment the next day explaining themselves",
    dateYYYYMMDD: "2022-08-29",
    significance: 2,
    imagePath: "assets/misc/cnbc-2022-08-30.PNG",
    tags: ["propaganda", "cnbc", "joe kernan", "melissa lee", "reddit", "superstonk"],
    types: [TimelineEventType.MEDIA],
    urls: [
      { title: 'Financial Media on GME', isLocal: true, url: '/media-vs-gme', },
      { title: 'CNBC cuts off guest immediately for mentioning “shorts covering” - Monday 8/29 ', isLocal: false, url: 'https://www.reddit.com/r/Superstonk/comments/x0o988/cnbc_cuts_off_guest_immediately_for_mentioning/', },
      { title: "It's glorious! CNBC feeling the need to explain themselves. ", isLocal: false, url: 'https://www.reddit.com/r/Superstonk/comments/x1qgr9/its_glorious_cnbc_feeling_the_need_to_explain/', },
    ],
    showInViews: ["CURRENT"],
  },
  {
    title: "GameStop Does a 4-for-1 Stock Split in the Form of a Stock Dividend",
    shortTitle: "",
    description: "",
    dateYYYYMMDD: "2022-07-21",
    significance: 2,
    tags: ["corporate", "stock split", "split"],
    types: [TimelineEventType.CORP],
    showInViews: [],
  },
  {
    title: "DRSGME.org Published by GameStop Investors",
    shortTitle: "",
    description: "Website created by GME shareholders",
    dateYYYYMMDD: "2022-03-18",
    significance: 2,
    imagePath: "",
    tags: ["[drs", "drsgme", "superstonk", "community", "investors", "]"],
     types: [TimelineEventType.DRS],
    showInViews: [],
  },
  {
    title: "Naked Shorts, Yea",
    shortTitle: "",
    description: "In response to the statement: 'There are a lot of short sellers borrowing stock that they didnt have,' Melissa Lee of CNBC replied: 'Naked shorts, yea.'",
    dateYYYYMMDD: "2021-06-04",
    significance: 2,
    imagePath: "assets/misc/melissa-lee-naked-shorts.png",
    tags: ["media", "propaganda", "naked short selling", "shorts", "wall street", "hedge funds"],
    types: [TimelineEventType.MEDIA],
    urls: [
      { title: 'Financial Media on GME', isLocal: true, url: '/media-vs-gme', },
      { title: 'CNBC cuts off guest immediately for mentioning “shorts covering” - Monday 8/29 ', isLocal: false, url: 'https://www.reddit.com/r/Superstonk/comments/nshffm/naked_shorts_just_confirmed_by_the_enemies/' },
      { title: "Melissa Lee - “Naked Shorts, Yeah”", isLocal: false, url: 'https://www.youtube.com/watch?v=XpHcA8Y1mWI&t=94s', },
    ],
    showInViews: ["CURRENT",],
  },
  {
    title: "RC Ventures writes to the GameStop Board of Directors",
    shortTitle: "RC Letter",
    description: "Subject: Maximizing Stockholder Value by Becoming the Ultimate Destination for Gamers, GAMESTOPS LEADERSHIP MUST PROMPTLY PIVOT FROM A BRICK-AND-MORTAR MINDSET TO A TECHNOLOGY-DRIVEN VISION",
    dateYYYYMMDD: "2020-11-16",
    significance: 2,
    tags: ["ryan cohen", "letter",],
    types: [TimelineEventType.RC],
    urls: [{ title: 'A turnaround vision', isLocal: true, url: "/turnaround", }],
    showInViews: [],
  },
  {
    title: "RC Ventures LLC purchases 9% of GameStop",
    shortTitle: "RC buys GME",
    description: "Ryan Cohen enters the scene, buying a 9% stake in GameStop, becoming the single largest individual shareholder.",
    dateYYYYMMDD: "2020-08-18",
    significance: 2,
    imagePath: "assets/misc/ryan-cohen-loading.jpg",
    tags: ["ryan cohen", "insiders"],
    types: [TimelineEventType.RC],
    urls: [{ title: 'Ryan Cohen Buys GME', isLocal: true, url: "/turnaround", }],
    showInViews: ["CURRENT", "CURRENT_MOBILE", "HISTORIC", "SNEEZE", "SNEEZE_MOBILE"],
  },
  {
    title: "Playstation 5 released",
    shortTitle: "",
    description: "Playstation 5 released",
    dateYYYYMMDD: "2020-11-19",
    tags: ["playstation", "sony", "video game", "console",],
    significance: 2,
    types: [TimelineEventType.OTHER],
    showInViews: ["HISTORIC"],
  },
  {
    title: "Xbox Series X|S released",
    shortTitle: "",
    description: "Xbox Series X|S released",
    dateYYYYMMDD: "2020-11-10",
    tags: ["microsoft", "xbox", "video game", "console"],
    significance: 2,
    types: [TimelineEventType.OTHER],
    showInViews: ["HISTORIC"],
  },
  {
    title: "Wii U released",
    shortTitle: "",
    description: "Wii U released",
    dateYYYYMMDD: "2012-11-18",
    tags: ["nintendo", "video game", "console"],
    significance: 2,
    types: [TimelineEventType.OTHER],
    showInViews: ["HISTORIC"],
  },
  {
    title: "Playstation Vita (PS Vita) released",
    shortTitle: "",
    description: "Playstation Vita (PS Vita) released",
    dateYYYYMMDD: "2012-02-22",
    tags: ["playstation", "sony", "video game", "console",],
    significance: 2,
    types: [TimelineEventType.OTHER],
    showInViews: ["HISTORIC"],
  },
  {
    title: "Nintendo 3DS released",
    shortTitle: "",
    description: "Nintendo 3DS released",
    dateYYYYMMDD: "2011-03-27",
    tags: ["nintendo", "video game", "console",],
    significance: 2,
    types: [TimelineEventType.OTHER],
    showInViews: ["HISTORIC"],
  },
  {
    title: "Playstation Portable released",
    shortTitle: "",
    description: "Playstation Portable released",
    dateYYYYMMDD: "2004-12-12",
    significance: 2,
    imagePath: "",
    tags: ["playstation", "sony", "video game", "console"],
    types: [TimelineEventType.OTHER],
    showInViews: ["HISTORIC"],
  },
  {
    title: "Nintendo DS released",
    shortTitle: "",
    description: "Nintendo DS released",
    dateYYYYMMDD: "2004-11-21",
    tags: ["nintendo", "video game", "console"],
    significance: 2,
    types: [TimelineEventType.OTHER],
    showInViews: ["HISTORIC"],
  },

  {
    title: "DFV original post in r/WallStreetBets - $114 K",
    shortTitle: "DFV original post",
    description: "Keith Gill posts for the first time on reddit as DeepFuckingValue",
    dateYYYYMMDD: "2019-09-08",
    significance: 1,
    imagePath: "",
    tags: ["[dfv", "yolo", "roaringkitty"],
    // urls: ["[https://www.reddit.com/r/wallstreetbets/comments/d1g7x0/hey_burry_thanks_a_lot_for_jacking_up_my_cost/}}Hey Burry thanks a lot for jacking up my cost basis", "]"],
    types: [TimelineEventType.SOCIAL_MEDIA],
    showInViews: ["SNEEZE", "SNEEZE_MOBILE"],
  },
  {
    title: "Ryan Cohen Receives 3 Board Seats, Becomes Board Member",
    shortTitle: "",
    description: "",
    dateYYYYMMDD: "2021-01-11",
    significance: 1,
    imagePath: "",
    tags: ["ryan cohen"],
    // urls: ["[https://www.dallasnews.com/business/retail/2021/01/11/gamestop-stock-soars-with-activist-ryan-cohen-gaining-board-seats/}}GameStop stock soars with activist Ryan Cohen gaining board seats", "]"],
    types: [TimelineEventType.RC],
    showInViews: ["SNEEZE", "SNEEZE_MOBILE", ],
  },
  {
    title: "GameStop Announces Ryan Cohen will become Chairman of the Board of Directors",
    shortTitle: "",
    description: "",
    dateYYYYMMDD: "2021-04-08",
    significance: 3,
    imagePath: "",
    tags: ["ryan cohen"],
    // urls: ["[https://www.bloomberg.com/news/articles/2021-04-08/gamestop-plans-to-make-activist-ryan-cohen-chairman-shares-rise/}}GameStops Cohen to Be Chairman, Cementing Sway", "Stock Rises", "]"],
    types: [TimelineEventType.RC],
    showInViews: ["SNEEZE", "SNEEZE_MOBILE"],
  },
];
